version: 2.1

orbs:
  python: circleci/python@0.3.2

workflows:
  main:
    jobs:
      - build-and-test


jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: "Run"
          command: |
            pip install pytest
            pip install flake8

            flake8 .
            pytest .


